[mypy]
ignore_missing_imports = True
python_version = 3.11
show_error_codes = True
show_column_numbers = True
mypy_path = .
explicit_package_bases = True
exclude = ^tests/|^app/database/migrations/
follow_imports = silent
disable_error_code = name-defined, attr-defined

[pydantic-mypy]
init_forbid_extra = False
warn_untyped_fields = True

[mypy-app.database.migrations.*]
ignore_errors = True

[mypy-app.tests.*]
ignore_errors = True
